# Generated by Django 5.0.6 on 2025-11-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='الرقم التسلسلي')),
                ('device_type', models.CharField(choices=[('LAPTOP', 'لابتوب'), ('DESKTOP', 'كمبيوتر مكتبي'), ('PRINTER', 'طابعة'), ('SCANNER', 'ماسح ضوئي'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع الجهاز')),
                ('model', models.CharField(max_length=100, verbose_name='موديل الجهاز')),
                ('date_assigned', models.DateField(blank=True, null=True, verbose_name='تاريخ التخصيص')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='مخصص للموظف')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('NEW', 'جديدة'), ('IN_PROGRESS', 'قيد المعالجة'), ('PENDING', 'معلقة'), ('RESOLVED', 'تم الحل'), ('CLOSED', 'مغلقة')], default='NEW', max_length=20, verbose_name='حالة التذكرة')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('URGENT', 'عاجلة')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolution', models.TextField(blank=True, verbose_name='الحل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='معين إلى')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='rols_app.device', verbose_name='الجهاز المتأثر')),
            ],
            options={
                'verbose_name': 'تذكرة',
                'verbose_name_plural': 'التذاكر',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rols_app.ticket', verbose_name='التذكرة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
            },
        ),
    ]
